name: Deploy to VPS on Push to development

on:
  workflow_dispatch: 

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest
    environment: CICD

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_KEY }}

    - name: Debug - Verify SSH agent
      run: ssh-add -l

    - name: Archive build artifacts
      run: tar -czf build.tar.gz dist/

    - name: Upload build artifacts to VPS
      run: |
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/www/

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} 'bash /www/nxems-ci.sh'
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}

    - name: Debug - Post-deployment
      if: always()
      run: |
        echo "Deployment step status: ${{ job.status }}"
