name: Test VPS Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-vps-connection:
    name: Test SSH connection to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Create SSH key file
      run: |
        echo "${{ secrets.VPS_KEY }}" | tr -d '\r' > ssh_key
        chmod 600 ssh_key

    - name: Test SSH connection to VPS
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "echo 'Connected to VPS successfully!'"

    - name: Cleanup SSH key
      run: rm ssh_key
