name: Test SCP Connection

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-scp-connection:
    name: Test SCP connection to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Create SSH key file
      run: |
        echo "${{ secrets.VPS_KEY }}" | tr -d '\r' > ssh_key
        chmod 600 ssh_key

    - name: Create a test file
      run: echo "This is a test file" > test_file.txt

    - name: Test SCP connection to VPS
      run: |
        scp -o StrictHostKeyChecking=no -i ssh_key test_file.txt ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/tmp/

    - name: Cleanup SSH key and test file
      run: |
        rm ssh_key
        rm test_file.txt
