name: Deploy to Eravend Server

on:
  push: 
    branches:
      - development

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest
    environment: CICD

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'
        
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_KEY }}

    - name: Archive build artifacts
      run: tar -czf build.tar.gz -C dist/apps/web .

    - name: Upload build artifacts to VPS
      run: |
        scp -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/www/wwwroot/ems-production

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << EOF
          cd /www/wwwroot/ems-production
          find . -mindepth 1 -not -path './node_modules*' -not -name 'build.tar.gz' -exec rm -rf {} +
          tar -xzf build.tar.gz
          rm build.tar.gz
          
          # Stop the existing process
          pid=$(lsof -t -i:4000)
          if [ ! -z "$pid" ]; then
            echo "Stopping process on port 4000"
            sudo kill -15 $pid
            sleep 5
            if kill -0 $pid 2>/dev/null; then
              echo "Process did not stop gracefully, force killing"
              sudo kill -9 $pid
            fi
          else
            echo "No process found on port 4000"
          fi
          
          # Start the new process
          echo "Starting new process"
          nohup yarn start --port 4000 > /www/server/nodejs/vhost/logs/ems-prod.log 2>&1 &
          echo $! > /www/server/nodejs/vhost/pids/ems-prod.pid
          sleep 5
          
          # Check if the new process is running
          if kill -0 $(cat /www/server/nodejs/vhost/pids/ems-prod.pid) 2>/dev/null; then
            echo "New process started successfully"
          else
            echo "Failed to start new process"
            cat /www/server/nodejs/vhost/pids/ems-prod.pid
            exit 1
          fi
        EOF
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}

    - name: Debug - Post-deployment
      if: always()
      run: |
        echo "Deployment step status: ${{ job.status }}"