name: Build and Deploy to VPS on Push to development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: self-hosted
    environment: CICD

    env:
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_IP: ${{ secrets.VPS_IP }}
      VPS_DEPLOY_PATH: /www/wwwroot/        
      VPS_PROJECT_PATH: /www/wwwroot/      

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'  

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm build

    - name: Archive build artifacts
      run: |
        tar -czf build.tar.gz dist/apps/web

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Copy build to server
      run: |
        scp -o StrictHostKeyChecking=no build.tar.gz $VPS_USER@$VPS_IP:$VPS_DEPLOY_PATH

    # - name: Deploy on server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_IP bash -c "'
    #       cd $VPS_PROJECT_PATH
    #       tar -xzf $VPS_DEPLOY_PATH/build.tar.gz -C .
    #       # Run additional deployment scripts here
    #     '"
