name: Deploy to Eravend Server

on:
  push: 
    branches:
      - development

jobs:
  deploy:
    name: Build and Deploy to VPS
    runs-on: ubuntu-latest
    environment: CICD

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.10.0'  
        
    - name: Install PNPM
      run: npm i -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build the project
      run: pnpm run build

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Archive build artifacts
      run: tar -czf build.tar.gz -C dist/apps/web .

    - name: Upload build artifacts to VPS
      run: |
        sshpass -p "${{ secrets.VPS_KEY }}" scp -P 1076 -o StrictHostKeyChecking=no build.tar.gz ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/home/shahid/ems-production

    - name: Deploy to VPS with elevated permissions
      run: |
        sshpass -p "${{ secrets.VPS_KEY }}" ssh -p 1076 -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << EOF
          sudo su
          cd /home/shahid/ems-production
          find . -mindepth 1 -not -path './node_modules*' -not -name 'build.tar.gz' -exec rm -rf {} +
          tar -xzf build.tar.gz
          rm build.tar.gz
        EOF
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_IP: ${{ secrets.VPS_IP }}
        VPS_PASSWORD: ${{ secrets.VPS_KEY }}

    - name: Debug - Post-deployment
      if: always()
      run: |
        echo "Deployment step status: ${{ job.status }}"
